// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: ['intro', {type: 'autogenerated', dirName: 'tutorial-basics'}, {type: 'autogenerated', dirName: 'tutorial-extras'}],

  odooSidebar: [
    'odoo/index',
    {
      type: 'category',
      label: '部署/配置',
      collapsible: true,
      collapsed: true,
      link: {
        type: 'generated-index',
        title: 'Odoo 部署/配置',
        description: 'Odoo的安装部署及配置',
      },
      items: [{type: 'autogenerated', dirName: 'odoo/install'}]
    },
    {
      type: 'category',
      label: '开发笔记',
      collapsible: true,
      collapsed: false,
      link: {
        type: 'generated-index',
        title: '开发笔记',
        description: '记录Odoo ERP系统的开发实践与深度优化，分享从模块定制、性能调优到系统集成的全流程解决方案。基于实际项目经验，总结可复用的代码模式与避坑指南，助力开发者与企业高效落地Odoo。',
      },
      items: [
        'odoo/dev_notes/built_in_function',
        {
          type: 'category',
          label: '视图',
          items: [
            'odoo/dev_notes/views/kanban_view',
            'odoo/dev_notes/views/search_view',
            'odoo/dev_notes/views/view_and_xml_restrictions',
            'odoo/dev_notes/views/create_a_new_view_v17',
          ]
        },
        {
          type: 'category',
          label: '模型',
          items: [
            'odoo/dev_notes/models/model_email_template',
            'odoo/dev_notes/models/constraints',
            'odoo/dev_notes/models/create_database_view',
          ]
        },
        {
          type: 'category',
          label: 'Odoo原生解析',
          items: [
            {
                type: 'category',
                label: 'Fields',
                items: [
                    'odoo/dev_notes/source_code_analysis/fields/file_handler',
                    'odoo/dev_notes/source_code_analysis/fields/binary_field_analysis',
                ]
            },
            {
                type: 'category',
                label: 'Views',
                items: [
                    'odoo/dev_notes/source_code_analysis/views/list_view_open_record_dynamic',
                    'odoo/dev_notes/source_code_analysis/views/views_binding_actions',
                ]
             },
             {
                type: 'category',
                label: 'Components',
                items: [
                    'odoo/dev_notes/source_code_analysis/components/action_menus_analyze',
                ]
              },
            'odoo/dev_notes/check_credentials',
            'odoo/dev_notes/xml_rpc',
            'odoo/dev_notes/owl_dialog',
            'odoo/dev_notes/utils_search_fuzzyLookup',
            'odoo/dev_notes/owl_dropdown',
            'odoo/dev_notes/owl_useSortable',            
            'odoo/dev_notes/command_palette',
            'odoo/dev_notes/file_viewer_v17',            
          ]
        },
        {
          type: 'category',
          label: '前端',
          items: [
           {
             type: 'category',
             label: 'OWL',
             items: [
                'odoo/dev_notes/front-end/some_owl_usages',
                'odoo/dev_notes/front-end/owl_custom_page_simple',
                'odoo/dev_notes/front-end/owl_patch',
                'odoo/dev_notes/front-end/owl_create_dialog',
                'odoo/dev_notes/front-end/owl_use_external_libraries',
                'odoo/dev_notes/front-end/owl_confirmation_dialog_with_input',
                'odoo/dev_notes/front-end/owl_record_filter',
             ]
           },
           {
             type: 'category',
             label: 'Views',
             items: [
                'odoo/dev_notes/front-end/views/form_view_usage',
                'odoo/dev_notes/front-end/views/list_view_extension',
                'odoo/dev_notes/front-end/views/x2many_treeview_unlink_button_position',
                'odoo/dev_notes/front-end/views/listview_select_same_group_records',
                'odoo/dev_notes/front-end/views/lazy_relation_model',
                'odoo/dev_notes/front-end/views/form_view_do_not_auto_save',
                'odoo/dev_notes/front-end/views/disable_for_view_useEffect_v16',
                'odoo/dev_notes/front-end/views/form_view_record_readonly_domain_thinking_v16',
                'odoo/dev_notes/front-end/views/graph_view_extension',
             ]
           },
           {
             type: 'category',
             label: 'Fields',
             items: [
                'odoo/dev_notes/front-end/fields/integer_field_extend',
                'odoo/dev_notes/front-end/fields/float_field_extend',
                'odoo/dev_notes/front-end/fields/x2many_field_extend',
                'odoo/dev_notes/front-end/fields/binary_field_extension',
             ]
           },
          ]
        },
        {
          type: 'category',
          label: 'Custom Module',
          items: [
            'odoo/dev_notes/simplest_systray',
            'odoo/dev_notes/systray_quick_menu',
            'odoo/dev_notes/x2many_list_export_all',
            'odoo/dev_notes/custom_module/ir_actions_report_docx',
            'odoo/dev_notes/custom_module/custom_popover_widget',
          ]
        },
        'odoo/dev_notes/translate',
        'odoo/dev_notes/code_quick_reference_table',
        'odoo/dev_notes/common/odoo_locust_stress_test',
        'odoo/dev_notes/common/add_table_change_log',
        'odoo/dev_notes/python_code_snippet',
        'others/python_patterns',
        'others/git_commit_message',
      ]
    }
  ],

  projectManagerSidebar: [{type: 'autogenerated', dirName: 'project_manager'}],
//  odooSidebar: [
//    'odoo/index',
//    {
//      type: 'category',
//      label: '部署/配置',
//      collapsed: false,
//      link:{
//        type: 'generated-index',
//        title: 'Odoo 部署/配置',
//        description: "Odoo的安装部署及配置"
//      },
//      items: [
//        'odoo/install/01-config_description',
//      ]
//    }
//  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
