// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: ['intro', {type: 'autogenerated', dirName: 'tutorial-basics'}, {type: 'autogenerated', dirName: 'tutorial-extras'}],

  odooSidebar: [{type: 'autogenerated', dirName: 'odoo'}],

  projectManagerSidebar: [{type: 'autogenerated', dirName: 'project_manager'}],
//  odooSidebar: [
//    'odoo/index',
//    {
//      type: 'category',
//      label: '部署/配置',
//      collapsed: false,
//      link:{
//        type: 'generated-index',
//        title: 'Odoo 部署/配置',
//        description: "Odoo的安装部署及配置"
//      },
//      items: [
//        'odoo/install/01-config_description',
//      ]
//    }
//  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
